options:
  formatter: stylish
  merge-default-rules: true
files:
  include: './src/styles/**/*.scss'
rules:
  indentation:
    - 2
    -
      size: 4
  no-css-comments: 0
  class-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedbem
  property-sort-order:
    - 1
    -
      order: smacss
