version: '3'

volumes:
  lnmp_mysql_data:
  lnmp_redis_data:

networks:
  front:
  back:

services:
  nginx:
    container_name: lnmp-nginx
    build:
      context: ./
      dockerfile: ./config/docker/dockerfiles/nginx/Dockerfile
      args:
        TZ: ${TZ:-America/New_York}
        NGINX_VERSION: ${NGINX_VERSION:-alpine}
    ports:
      - "${WP_PORT:-8000}:80"
    volumes:
      - .:/var/www/html:rw,cached
      - ./config/docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro,cached
      - ./config/docker/etc/nginx/global:/etc/nginx/global:ro,cached
      - ./config/docker/etc/nginx/wordpress:/etc/nginx/wordpress:ro,cached
      - ./config/docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro,cached
      - ./logs/nginx:/var/log/nginx:rw,delegated
    restart: always
    depends_on:
      - php
    networks:
      - front

  php:
    container_name: lnmp-php
    build:
      context: ./
      dockerfile: ./config/docker/dockerfiles/php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-7-fpm-alpine}
        MEMCACHED_EXT_VERSION: ${MEMCACHED_EXT_VERSION:-3.1.3}
        REDIS_EXT_VERSION: ${REDIS_EXT_VERSION:-4.1.1}
        XDEBUG_EXT_VERSION: ${XDEBUG_EXT_VERSION:-beta}
        TZ: ${TZ:-America/New_York}
    volumes:
      - .:/var/www/html:rw,cached
      - ./config/docker/dockerfiles/php/.bashrc:/root/.bashrc:rw,cached
      - ./config/docker/etc/php/php.ini:/usr/local/etc/php/php.ini:rw,cached
      - ./config/docker/etc/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:ro,cached
      - ./config/docker/etc/php/conf.d/mysqli.ini:/usr/local/etc/php/conf.d/mysqli.ini:ro,cached
      - ./config/docker/etc/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro,cached
      - ./config/docker/etc/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro,cached
      - ./logs/php:/var/log/php:rw,delegated
    # for xdebug
    expose:
      - "9001"
    environment:
      WP_HOME: ${WP_HOME:-127.0.0.1:8000}
      WP_HOST: ${WP_HOST:-127.0.0.1}
      WP_PORT: ${WP_PORT:-8000}
      DB_NAME: ${DB_NAME:-wordpress}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_HOST: ${DB_HOST:-mysql}
      DB_PORT: ${DB_PORT:-3306}
      DB_CHARSET: ${DB_CHARSET:-utf8mb4}
      DB_PREFIX: ${DB_PREFIX:-wp_}
      CACHE_HOST: ${REDIS_HOST:-redis}
      CACHE_PORT: ${REDIS_PORT:-6379}
      CACHE_PASSWORD: ${REDIS_PASSWORD:-}
      XDEBUG_CONFIG: remote_host=192.168.65.2
    # cap and privileged needed for slowlog
    cap_add:
      - SYS_PTRACE
    privileged: true
    restart: always
    depends_on:
      - mysql
      - redis
    networks:
      - front
      - back

  mysql:
    container_name: lnmp-mysql
    image: mariadb:${MARIADB_VERSION:-latest}
    ports:
      - '8001:3306'
    volumes:
      - lnmp_mysql_data:/var/lib/mysql:rw,delegated
      - ./config/docker/etc/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro,cached
    environment:
      MYSQL_DATABASE: ${DB_NAME:-wordpress}
      MYSQL_USER: ${DB_USER:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: root
    restart: always
    networks:
      - back

  redis:
    container_name: lnmp-redis
    image: redis:${REDIS_VERSION:-alpine}
    ports:
      - '6379:6379'
    volumes:
      - lnmp_redis_data:/data:rw,delegated
      - ./config/docker/etc/redis/redis.conf:/etc/redis.conf:ro,cached
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      - back
