#!/bin/bash

# Exit immediately on errors
set -e

function success () {
  echo -e "[ \033[00;32mOK\033[0m ] $1\n"
}

DB=$(wp --allow-root dotenv get DB_NAME)
DATE=$(date +%Y%m%d_%H%M%S)

USER="$(wp --allow-root dotenv get DB_USER)"
PASS="$(wp --allow-root dotenv get DB_PASSWORD)"
HOST="$(wp --allow-root dotenv get DB_HOST | sed -E "s/^([^\:]+).+/\1/g")"

CLIENT="mysql -u $USER -p$PASS -h $HOST $DB -Ns"

(
  echo "CREATE DATABASE ${DB}_$DATE CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

  echo "USE $DB;"

  ${CLIENT} -e 'SHOW TABLES;' | while read TABLE; do
    echo "RENAME TABLE $DB.$TABLE TO ${DB}_$DATE.$TABLE;"
  done

  echo 'FLUSH PRIVILEGES;'

) | ${CLIENT}

success "Renamed ${DB} to ${DB}_$DATE"

exit 0;
